

name: My Workflow

on: [push]

jobs:
  hello-nedap:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Nedap
        run: echo "Hello Nedap"

      - name: Something else
        run: echo


